name: "TBD"
title: "TBD"
remote_theme: pages-themes/tactile@v0.2.0
timezone: Canada/Eastern
future: true
show_downloads: true
exclude: [tbd.gemspec, Gemfile, Gemfile.lock]
github:
  zip_url: https://github.com/rd2/tbd/releases/download/v2.4.1/tbd.zip
  tar_url: https://github.com/rd2/tbd/releases/download/v2.4.1/tbd.tar.gz
lsi: false
safe: true
source: [https://github.com/rd2/tbd]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
